export interface IGenresIcons {
  id: number
  name: string
}

export type IGenres =
  | 'anime'
  | 'biography'
  | 'militant'
  | 'western'
  | 'military'
  | 'detective'
  | 'children'
  | 'adults'
  | 'documentary'
  | 'drama'
  | 'game'
  | 'history'
  | 'comedy'
  | 'concert'
  | 'shortfilm'
  | 'criminal'
  | 'melodrama'
  | 'music'
  | 'animatedfilm'
  | 'musical'
  | 'news'
  | 'adventure'
  | 'realitytv'
  | 'family'
  | 'sport'
  | 'talkShow'
  | 'thriller'
  | 'horror'
  | 'fiction'
  | 'filmnoir'
  | 'fantasy'
  | 'ceremony'
