export type INameIcons =
  | 'arrowLeft'
  | 'arrowRight'
  | 'call'
  | 'copy'
  | 'favoriteAdd'
  | 'favoriteRemove'
  | 'language'
  | 'notify'
  | 'playOutline'
  | 'profile'
  | 'search'
  | 'share'
  | 'close'

export type INameIconsExt = 'top10' | '18plus'
