export type INameIcons =
  | 'arrowLeft'
  | 'arrowRight'
  | 'call'
  | 'copy'
  | 'favoriteAdd'
  | 'favoriteRemove'
  | 'language'
  | 'notify'
  | 'playOutline'
  | 'profile'
  | 'search'
  | 'share'
  | 'close'
  | 'smart'
  | 'quality'
  | 'drama'
  | 'rating'
  | 'similar'

export type INameIconsExt =
  | 'top10'
  | '18plus'
  | 'user'
  | 'googlePlay'
  | 'appStore'
  | 'dislike'
